/*Command to create database.*/
CREATE DATABASE ASSIGNMENT;

/*Command to use database.*/
USE ASSIGNMENT;
 
/*Command to create table.*/
CREATE TABLE SHORTSS(
	USER_ID INT,
	U_NAME VARCHAR(20),
	U_EMAIL VARCHAR(20),
	U_PNO INT,
	PRESENT_ADDRESS VARCHAR(20),
	PERMANENT_ADDRESS VARCHAR(20),
	AADHAR_NO INT,
	VIDEO_DURATION VARCHAR(10),
	UPLOAD_DATE VARCHAR(20),
	VIEWS VARCHAR(250)
);

CREATE TABLE VIDEOS (
	USER_ID INT,
    VIDEO_ID INT,
    VIDEO_TITLE VARCHAR(50),
    UPLOADER_NAME VARCHAR(20),
    UPLOADER_EMAIL VARCHAR(50),
    UPLOADER_PHONE INT,
    UPLOAD_LOCATION VARCHAR(50),
    FILE_SIZE_MB DECIMAL(10, 2),
    UPLOAD_DATE TIMESTAMP,
    TOTAL_VIEWS INT
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(50),
    CUSTOMER_EMAIL VARCHAR(50),
    CUSTOMER_ADDRESS VARCHAR(50),
    PHONE_NUMBER VARCHAR(15),
    BILLING_ADDRESS VARCHAR(100),
    SHIPPING_ADDRESS VARCHAR(100),
    CUSTOMER_TYPE VARCHAR(20),
    REGISTRATION_DATE DATE,
    LAST_PURCHASE_DATE DATE
);

CREATE TABLE FANS (
    FAN_ID INT,
    FAN_NAME VARCHAR(50),
    MANUFACTURER VARCHAR(50),
    MODEL VARCHAR(50),
    COLOR VARCHAR(20),
    SIZE VARCHAR(20),
    BLADE_MATERIAL VARCHAR(50),
    POWER_SOURCE VARCHAR(20),
    NUMBER_OF_SPEEDS INT,
    PRICE INT
);

CREATE TABLE SPEAKERS (
    SPEAKER_ID INT,
    SPEAKER_NAME VARCHAR(50),
    BRAND VARCHAR(50),
    MODEL VARCHAR(50),
    COLOR VARCHAR(20),
    CONNECTIVITY_TYPE VARCHAR(50),
    SPEAKER_TYPE VARCHAR(20),
    POWER_SOURCE VARCHAR(20),
    NUMBER_OF_DRIVERS INT,
    PRICE INT
);

CREATE TABLE LAPTOPS (
    LAPTOP_ID INT,
    LAPTOP_NAME VARCHAR(50),
    BRAND VARCHAR(50),
    MODEL VARCHAR(50),
    PROCESSOR VARCHAR(50),
    RAM_SIZE_GB INT,
    STORAGE_CAPACITY_GB INT,
    SCREEN_SIZE_INCH DECIMAL(4, 1),
    OPERATING_SYSTEM VARCHAR(50),
    PRICE INT
);

CREATE TABLE CAMERAS (
    CAMERA_ID INT,
    CAMERA_NAME VARCHAR(50),
    BRAND VARCHAR(50),
    MODEL VARCHAR(50),
    MEGAPIXELS DECIMAL(5, 2),
    SENSOR_TYPE VARCHAR(50),
    LENS_TYPE VARCHAR(50),
    RESOLUTION VARCHAR(20),
    RECORDING_FORMAT VARCHAR(50),
    PRICE INT
);

CREATE TABLE UPS (
    UPS_ID INT,
    UPS_MODEL VARCHAR(50),
    BRAND VARCHAR(50),
    CAPACITY_VA INT,
    INPUT_VOLTAGE VARCHAR(20),
    OUTPUT_VOLTAGE VARCHAR(20),
    BATTERY_RUNTIME_MINUTES INT,
    CONNECTIVITY_TYPE VARCHAR(50),
    WEIGHT_KG VARCHAR(20),
    PRICE INT
);

CREATE TABLE SPECTACLES (
    SPECTACLES_ID INT,
    BRAND VARCHAR(50),
    MODEL VARCHAR(50),
    FRAME_MATERIAL VARCHAR(50),
    FRAME_COLOR VARCHAR(20),
    LENS_MATERIAL VARCHAR(50),
    LENS_TYPE VARCHAR(50),
    LENS_COLOR VARCHAR(20),
    SIZE VARCHAR(20),
    PRICE INT
);

CREATE TABLE HELMETS (
    HELMET_ID INT,
    BRAND VARCHAR(50),
    MODEL VARCHAR(50),
    HELMET_TYPE VARCHAR(50),
    SIZE VARCHAR(20),
    COLOR VARCHAR(20),
    MATERIAL VARCHAR(50),
    CERTIFICATION VARCHAR(50),
    VISOR_TYPE VARCHAR(50),
    PRICE INT
);

/*Command to rename the table name.*/
ALTER TABLE SHORTSS RENAME TO SHORTS;
ALTER TABLE CAMERAS RENAME TO CAMERA;
ALTER TABLE HELMETS RENAME TO HELMET;
ALTER TABLE LAPTOPS RENAME TO LAPTOP;
ALTER TABLE HELMETS RENAME TO HELMET;
ALTER TABLE SPECTACLES RENAME TO SPECT;

/*Command to drop 3rd column of the table.*/

ALTER TABLE SHORTS DROP COLUMN U_EMAIL;
ALTER TABLE CAMERA DROP COLUMN BRAND;
ALTER TABLE HELMET DROP COLUMN MODEL;

/*Command to change datatype of column*/

ALTER TABLE SHORTS MODIFY COLUMN PRESENT_ADDRESS INT;
ALTER TABLE CAMERA MODIFY COLUMN MODEL INT;

/*Command to change datatype of column*/

ALTER TABLE SHORTS MODIFY COLUMN PERMANENT_ADDRESS VARCHAR(500);
ALTER TABLE CAMERA MODIFY COLUMN MEGAPIXELS VARCHAR(100);

/*Command to change name of the database*/


SHOW TABLES;


